 #
 # Copyright © Lyra Network.
 # This file is part of PayZen Bundle for Symfony. See COPYING.md for license details.
 #
 # @author    Lyra Network (https://www.lyra-network.com/)
 # @copyright Lyra Network
 # @license   https://opensource.org/licenses/mit-license.html The MIT License (MIT)
 #

services:
    payzen_service:
        class: Lyra\PayzenBundle\Payzen\PayzenService
        arguments: ['%site_id%','%test_mode%', '%algo_signature%', '%kr_popin%', '%test_password%', '%prod_password%', '%test_public_key%', '%prod_public_key%' 
        , '%hmac_256_test_key%', '%hmac_256_key_prod%', '%client_javascript_url%', '%api_rest_url%', '%kr_post_url_refused%', '%kr_post_url_success%','%kr_language']
        public: true

    payzen_embedded_service:
        class: Lyra\PayzenBundle\Payzen\PayzenEmbeddedService
        arguments: ['%site_id%','%test_mode%', '%algo_signature%', '%kr_popin%', '%test_password%', '%prod_password%', '%test_public_key%', '%prod_public_key%'
        , '%hmac_256_test_key%',  '%hmac_256_key_prod%', '%client_javascript_url%', '%api_rest_url%', '%kr_post_url_refused%', '%kr_post_url_success%','%kr_language']
        public: true